### ISSUE TITLE
abs of humidity

### ISSUE THREAD

**Issue by KammutierSpule** [WurthElektronik/Sensors-SDK_STM32#1]
On WSEN_HIDS_EXAMPLE.c why the humidity is fabs(humidity) on HIDS_getHumidity_float example?

Should it be clamp to 0 instead?

**Comment by jeru-eiSmart** [comment]
Clamping to 100 and to 0 already happens in the WSEN_HIDS_2523020210001.c driver, function HIDS_convertHumidity_float() and HIDS_convertHumidity_int8(). 

So the "fabs()" function is not necessary here at all.
We'll correct that in the next release.
